### PR TITLE
Update nestbot/carbon

### PR DESCRIPTION
**Pull request by edwardleoni**
Update nestbot/carbon as otherwise package becomes incompatible with Laravel Backpack 4.0

### CODE REVIEW

**Comment by edwardleoni** [comment]
From Yonderhq.com

**Comment by bumperbox** [comment]
@edwardleoni we use this package with laravel 5.5 which has carbon1 dependency. I will have a look at see if it is possible to remove carbon altogether, but it may be a couple of days before I can look into it

**Comment by edwardleoni** [comment]
Right, I had to update it as my project actually uses Laravel 6.

In the mean time I'll just keep using my own branch

Thanks

**Comment by bumperbox** [comment]
I have removed the dependency on Carbon altogether
You can use version > 4.0.0

The following methods were affected
ExperienceSession::get_datetime
Price::get_date_valid_from
Price::get_date_valid_to
SessionsIndexed::get_next_scheduled_date

**Pull request closed without merging**
